table fact_financial_transactions
	lineageTag: 40740e13-4b59-4dfe-a9b2-3dd9751b3621
	sourceLineageTag: [university].[fact_financial_transactions]

	measure 'Total Revenue' =
			
			CALCULATE(
			    SUM(fact_financial_transactions[amount]),
			    fact_financial_transactions[transaction_type] = "Charge"
			)
		displayFolder: Financial Analytics
		lineageTag: 4e3696a7-f5fe-4f94-9b67-23ea7582869e

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Payments' = ```
			
			CALCULATE(
			    SUM(fact_financial_transactions[amount]),
			    fact_financial_transactions[transaction_type] = "Payment"
			)
			
			```
		displayFolder: Financial Analytics
		lineageTag: 7b0ac289-d63c-46ac-8151-80f33418c8f0

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outstanding Balance' = [Total Revenue] - [Total Payments]
		displayFolder: Financial Analytics
		lineageTag: e151d217-a8f2-48df-a82d-742854d6f542

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Scholarships' = ```
			
			CALCULATE(
			    SUM(fact_financial_transactions[amount]),
			    fact_financial_transactions[transaction_type] = "Credit"
			)
			
			```
		displayFolder: Financial Analytics
		lineageTag: 9b82bf99-6d0d-4c36-9009-0a1b9cd9b72c

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transaction Count' = COUNTROWS(fact_financial_transactions)
		formatString: 0
		displayFolder: Financial Analytics
		lineageTag: 29d7c2ec-d748-4cb8-969f-795b1c5f2a62

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Average Tuition' = ```
			
			CALCULATE(
			    AVERAGE(fact_financial_transactions[amount]),
			    fact_financial_transactions[transaction_type] = "Charge",
			    dim_fee_type[fee_type_name] = "Tuition"
			)
			
			```
		displayFolder: Financial Analytics
		lineageTag: 044ef8c7-ae83-494a-b306-613db7930d14

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overdue Amount' =
			
			CALCULATE(
			    SUM(fact_financial_transactions[amount]),
			    fact_financial_transactions[is_overdue] = TRUE()
			)
		displayFolder: Financial Analytics
		lineageTag: 4fb1384a-3def-4b80-9d7a-8e93e6bd1676

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Collection Rate' = DIVIDE([Total Payments], [Total Revenue])
		displayFolder: Financial Analytics
		lineageTag: 45c3063e-ecce-4c96-bdad-bd7c21db38c6

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Students with Overdue Balance' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_financial_transactions[student_key]),
			    fact_financial_transactions[is_overdue] = TRUE()
			)
		formatString: 0
		displayFolder: Financial Analytics
		lineageTag: a3d9cf55-32b4-4880-8c5b-c3610aa202fe

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Revenue Per Student' = DIVIDE([Total Revenue], [Unique Students])
		displayFolder: Per-Student Metrics
		lineageTag: a43a4376-09f6-41b5-a65d-ad64c4df9680

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MCs Per Student' = DIVIDE([Total MCs Earned], [Unique Students])
		displayFolder: Per-Student Metrics
		lineageTag: 0e371fc5-a9dd-4fda-8671-29c191009d6a

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GPA Per Student' =
			
			AVERAGEX(
			    VALUES(dim_student[student_key]),
			    CALCULATE(AVERAGE(fact_exam_results[grade_points]))
			)
		displayFolder: Per-Student Metrics
		lineageTag: 8dd0a7ca-cf13-4448-af81-c6d77ad7cb7e

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Exams Per Student' = DIVIDE([Exam Count], [Unique Students])
		displayFolder: Per-Student Metrics
		lineageTag: c8bd1ffc-5e28-46d5-949f-3407f597c66d

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Courses Per Student' = DIVIDE([Total Enrolments], [Unique Students])
		displayFolder: Per-Student Metrics
		lineageTag: b1ffb1b6-1970-422b-94bd-676850c91ba9

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Payment Rate' = DIVIDE([Total Payments], [Total Revenue])
		displayFolder: Per-Student Metrics
		lineageTag: 08ac46b7-6e80-4247-b55b-fa76a9a6c006

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scholarship Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(dim_student),
			        dim_student[scholarship_flag] = TRUE()
			    ),
			    COUNTROWS(dim_student)
			)
		displayFolder: Per-Student Metrics
		lineageTag: 71603939-c923-4d1d-a0ac-18ddf0184ef1

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column transaction_key
		dataType: int64
		formatString: 0
		lineageTag: 47a8d3d7-9a44-4301-84b0-97e3e40845df
		sourceLineageTag: transaction_key
		isDefaultLabel
		summarizeBy: sum
		sourceColumn: transaction_key

		annotation SummarizationSetBy = Automatic

	column student_key
		dataType: int64
		formatString: 0
		lineageTag: c0b69ab4-3f95-40e8-bb30-fd5c834fcb88
		sourceLineageTag: student_key
		summarizeBy: none
		sourceColumn: student_key

		annotation SummarizationSetBy = Automatic

	column fee_type_key
		dataType: int64
		formatString: 0
		lineageTag: a836a4dd-9bcf-491e-9b7c-6fe9f0c2f294
		sourceLineageTag: fee_type_key
		summarizeBy: none
		sourceColumn: fee_type_key

		annotation SummarizationSetBy = Automatic

	column academic_period_key
		dataType: int64
		formatString: 0
		lineageTag: 578cff3d-4915-4c84-ae2c-c787a366a785
		sourceLineageTag: academic_period_key
		summarizeBy: none
		sourceColumn: academic_period_key

		annotation SummarizationSetBy = Automatic

	column course_key
		dataType: int64
		formatString: 0
		lineageTag: 9d0bc70e-50c9-4be7-826f-02a6593f4cfd
		sourceLineageTag: course_key
		summarizeBy: none
		sourceColumn: course_key

		annotation SummarizationSetBy = Automatic

	column transaction_date_key
		dataType: int64
		formatString: 0
		lineageTag: 9a5f4934-d4ef-43cd-b396-41d7d26c2a45
		sourceLineageTag: transaction_date_key
		summarizeBy: none
		sourceColumn: transaction_date_key

		annotation SummarizationSetBy = Automatic

	column due_date_key
		dataType: int64
		formatString: 0
		lineageTag: f255f177-a937-4f31-acb2-4e086a68b0cf
		sourceLineageTag: due_date_key
		summarizeBy: sum
		sourceColumn: due_date_key

		annotation SummarizationSetBy = Automatic

	column transaction_id
		dataType: string
		lineageTag: d03c8775-fe6e-44b4-9979-ffa7bef2932f
		sourceLineageTag: transaction_id
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_type
		dataType: string
		lineageTag: 42bfb2a8-b283-44dd-b912-28629b052042
		sourceLineageTag: transaction_type
		summarizeBy: none
		sourceColumn: transaction_type

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: ca427ea4-d285-4f2c-b030-7ee2c29bb08f
		sourceLineageTag: amount
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column signed_amount
		dataType: double
		lineageTag: 0d4029b0-59f1-4657-8e47-dcc38b3debf3
		sourceLineageTag: signed_amount
		summarizeBy: sum
		sourceColumn: signed_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column currency
		dataType: string
		lineageTag: f63cfbaa-add1-4da1-ba07-45de8ba23e19
		sourceLineageTag: currency
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: fa704f8b-7bf6-4e5a-948b-3bdbaf0d7ac5
		sourceLineageTag: payment_method
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column reference_number
		dataType: string
		lineageTag: d7ec6ca0-aa8a-4c8a-a3e3-b89136814c1f
		sourceLineageTag: reference_number
		summarizeBy: none
		sourceColumn: reference_number

		annotation SummarizationSetBy = Automatic

	column is_overdue
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3fb25692-bd79-470c-98a4-5e0afd032bdf
		sourceLineageTag: is_overdue
		summarizeBy: none
		sourceColumn: is_overdue

		annotation SummarizationSetBy = Automatic

	column days_overdue
		dataType: int64
		formatString: 0
		lineageTag: d506b910-9f11-4b1b-9f2d-787508652f13
		sourceLineageTag: days_overdue
		summarizeBy: sum
		sourceColumn: days_overdue

		annotation SummarizationSetBy = Automatic

	column outstanding_balance_after
		dataType: double
		lineageTag: ae0a365d-13f1-49ac-8425-aea93bfde74e
		sourceLineageTag: outstanding_balance_after
		summarizeBy: sum
		sourceColumn: outstanding_balance_after

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_financial_transactions = entity
		mode: directLake
		source
			entityName: fact_financial_transactions
			schemaName: university
			expressionSource: 'DirectLake - university_lakehouse'

