table fact_exam_results
	lineageTag: 3417d640-3c63-44e5-beb1-83bad97d4eb1
	sourceLineageTag: [university].[fact_exam_results]

	measure 'Average GPA' = AVERAGE(fact_exam_results[grade_points])
		displayFolder: Academic Performance
		lineageTag: e2839eb3-3a82-4a94-bd4f-0f98b5197d7f

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Score' = AVERAGE(fact_exam_results[score_percentage])
		displayFolder: Academic Performance
		lineageTag: 2641c2e6-a219-4081-8769-71fd7bd2a4e0

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Weighted Score' = AVERAGE(fact_exam_results[weighted_score])
		displayFolder: Academic Performance
		lineageTag: 2be62416-e679-442a-bdff-7976f43236f4

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distinction Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_exam_results),
			        fact_exam_results[grade_letter] IN {"A+", "A", "A-"}
			    ),
			    COUNTROWS(fact_exam_results)
			)
		displayFolder: Academic Performance
		lineageTag: 95f1b729-faea-423a-bec0-6031a643a2cf

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exam Count' = COUNTROWS(fact_exam_results)
		formatString: 0
		displayFolder: Academic Performance
		lineageTag: fee90f04-f554-4dac-b955-d4635cd52278

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Pass Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_exam_results),
			        fact_exam_results[grade_letter] <> "F"
			    ),
			    COUNTROWS(fact_exam_results)
			)
		displayFolder: Academic Performance
		lineageTag: d5e9caf3-ee9d-4972-aebb-f765527324c0

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fail Count' =
			
			CALCULATE(
			    COUNTROWS(fact_exam_results),
			    fact_exam_results[grade_letter] = "F"
			)
		formatString: 0
		displayFolder: Academic Performance
		lineageTag: 0f689f2f-4fe2-4625-80c3-d90bd7e745a2

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Students at Academic Risk' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_enrollments[student_key]),
			    FILTER(
			        VALUES(fact_enrollments[student_key]),
			        CALCULATE(AVERAGE(fact_enrollments[course_gpa_points])) < 2.0
			    )
			)
		formatString: 0
		displayFolder: Academic Performance
		lineageTag: dc41927c-6de6-4a4f-b753-9c8df284f061

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Course Difficulty Index' = 1 - [Pass Rate]
		displayFolder: Academic Performance
		lineageTag: 0a4bbc5f-b364-4c93-b40c-fad1be3626d7

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column exam_result_key
		dataType: int64
		formatString: 0
		lineageTag: 6ee3c75f-5cfb-4f47-a726-a99b03821ece
		sourceLineageTag: exam_result_key
		isDefaultLabel
		summarizeBy: sum
		sourceColumn: exam_result_key

		annotation SummarizationSetBy = Automatic

	column student_key
		dataType: int64
		formatString: 0
		lineageTag: 146c711c-f370-4ad0-97ac-56032849d19d
		sourceLineageTag: student_key
		summarizeBy: none
		sourceColumn: student_key

		annotation SummarizationSetBy = Automatic

	column course_key
		dataType: int64
		formatString: 0
		lineageTag: 0f05a18f-bdbb-4b52-bacb-2b3a6cfb168b
		sourceLineageTag: course_key
		summarizeBy: none
		sourceColumn: course_key

		annotation SummarizationSetBy = Automatic

	column exam_type_key
		dataType: int64
		formatString: 0
		lineageTag: 44e22f66-e25c-44d3-8cf8-ffe4d6194aab
		sourceLineageTag: exam_type_key
		summarizeBy: none
		sourceColumn: exam_type_key

		annotation SummarizationSetBy = Automatic

	column academic_period_key
		dataType: int64
		formatString: 0
		lineageTag: a16a8e47-65e0-488a-be03-3298506c8efd
		sourceLineageTag: academic_period_key
		summarizeBy: none
		sourceColumn: academic_period_key

		annotation SummarizationSetBy = Automatic

	column staff_key
		dataType: int64
		formatString: 0
		lineageTag: 1c7a32a0-f7e7-4fb6-94ac-e7f9dcde2ace
		sourceLineageTag: staff_key
		summarizeBy: none
		sourceColumn: staff_key

		annotation SummarizationSetBy = Automatic

	column exam_date_key
		dataType: int64
		formatString: 0
		lineageTag: d9ded7dd-ec8d-44c8-9573-278760bf8f25
		sourceLineageTag: exam_date_key
		summarizeBy: none
		sourceColumn: exam_date_key

		annotation SummarizationSetBy = Automatic

	column submission_date_key
		dataType: double
		lineageTag: cc76e750-720f-4de8-944e-ab5f2c9cd755
		sourceLineageTag: submission_date_key
		summarizeBy: sum
		sourceColumn: submission_date_key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column raw_score
		dataType: double
		lineageTag: a2ee34d4-3dd5-4a18-a09e-7b6734688f19
		sourceLineageTag: raw_score
		summarizeBy: sum
		sourceColumn: raw_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_score
		dataType: double
		lineageTag: 5c014fdc-b525-44ab-9e8c-4d3836bc4baa
		sourceLineageTag: max_score
		summarizeBy: sum
		sourceColumn: max_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_percentage
		dataType: double
		lineageTag: 6e2aa12e-0ebb-47fc-9d0c-e70c359ea3ba
		sourceLineageTag: score_percentage
		summarizeBy: sum
		sourceColumn: score_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grade_letter
		dataType: string
		lineageTag: 6f76ef27-c537-478e-8ca1-cec8f04095b4
		sourceLineageTag: grade_letter
		summarizeBy: none
		sourceColumn: grade_letter

		annotation SummarizationSetBy = Automatic

	column grade_points
		dataType: double
		lineageTag: 775152f2-f613-47d6-88b9-a39a927368a9
		sourceLineageTag: grade_points
		summarizeBy: sum
		sourceColumn: grade_points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighting_pct
		dataType: double
		lineageTag: ce75f5a9-9a97-496b-8bba-507ecda4a5d8
		sourceLineageTag: weighting_pct
		summarizeBy: sum
		sourceColumn: weighting_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_score
		dataType: double
		lineageTag: 0c43761a-0e1b-4791-993e-0a390c5902fc
		sourceLineageTag: weighted_score
		summarizeBy: sum
		sourceColumn: weighted_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attempt_number
		dataType: int64
		formatString: 0
		lineageTag: 529c5029-4638-4b42-a1f1-2b507eefe492
		sourceLineageTag: attempt_number
		summarizeBy: sum
		sourceColumn: attempt_number

		annotation SummarizationSetBy = Automatic

	column is_supplementary
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e052d36f-533c-48c2-8e19-6512c10e3d4a
		sourceLineageTag: is_supplementary
		summarizeBy: none
		sourceColumn: is_supplementary

		annotation SummarizationSetBy = Automatic

	column submission_status
		dataType: string
		lineageTag: ec072658-bfc8-4221-a6ab-482f5c5bc46c
		sourceLineageTag: submission_status
		summarizeBy: none
		sourceColumn: submission_status

		annotation SummarizationSetBy = Automatic

	column grading_status
		dataType: string
		lineageTag: 2c03b60d-1cf8-46ef-8042-905b4671915f
		sourceLineageTag: grading_status
		summarizeBy: none
		sourceColumn: grading_status

		annotation SummarizationSetBy = Automatic

	partition fact_exam_results = entity
		mode: directLake
		source
			entityName: fact_exam_results
			schemaName: university
			expressionSource: 'DirectLake - university_lakehouse'

