table fact_enrollments
	lineageTag: 66ad7950-54ae-439b-8628-60724f4b47a1
	sourceLineageTag: [university].[fact_enrollments]

	measure 'Active Enrolments' = ```
			
			CALCULATE(
			    COUNTROWS(fact_enrollments),
			    fact_enrollments[enrollment_status] = "Enrolled"
			)
			
			```
		formatString: 0
		displayFolder: Enrolment Analytics
		lineageTag: 655f7254-cd09-44f3-8564-9033e41c32f3

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Total Enrolments' = COUNTROWS(fact_enrollments)
		formatString: 0
		displayFolder: Enrolment Analytics
		lineageTag: 781a83ab-27e4-4bea-948f-477bfbebf5ad

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Unique Students' = DISTINCTCOUNT(fact_enrollments[student_key])
		formatString: 0
		displayFolder: Enrolment Analytics
		lineageTag: c4ec4349-09f4-4a49-87af-cc663783d700

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Completion Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_enrollments),
			        fact_enrollments[enrollment_status] = "Completed"
			    ),
			    COUNTROWS(fact_enrollments)
			)
		displayFolder: Enrolment Analytics
		lineageTag: 6a034b64-46e8-4469-a94b-30e40c7a5449

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Withdrawal Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_enrollments),
			        fact_enrollments[enrollment_status] = "Withdrawn"
			    ),
			    COUNTROWS(fact_enrollments)
			)
		displayFolder: Enrolment Analytics
		lineageTag: db7833c1-2ae0-45be-8a0f-cfcae31dc94b

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total MCs Earned' = SUM(fact_enrollments[credit_points_earned])
		formatString: 0
		displayFolder: Enrolment Analytics
		lineageTag: 4054320f-a0d9-4a24-9aab-4e1d66c2152c

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Total MCs Attempted' = SUM(fact_enrollments[credit_points_attempted])
		formatString: 0
		displayFolder: Enrolment Analytics
		lineageTag: 9ac0d4f8-1290-4c11-84c6-c28391f06cec

		changedProperty = Name

		changedProperty = DisplayFolder

	column enrollment_key
		dataType: int64
		formatString: 0
		lineageTag: 6f8e8cb1-e1d2-452c-ad40-e4485c3168c6
		sourceLineageTag: enrollment_key
		summarizeBy: sum
		sourceColumn: enrollment_key

		annotation SummarizationSetBy = Automatic

	column student_key
		dataType: int64
		formatString: 0
		lineageTag: c2ca0f72-fcd7-4812-a432-b09c835ef563
		sourceLineageTag: student_key
		summarizeBy: none
		sourceColumn: student_key

		annotation SummarizationSetBy = Automatic

	column course_key
		dataType: int64
		formatString: 0
		lineageTag: 5861ea96-f54e-406b-95e2-13c323b54c11
		sourceLineageTag: course_key
		summarizeBy: none
		sourceColumn: course_key

		annotation SummarizationSetBy = Automatic

	column academic_period_key
		dataType: int64
		formatString: 0
		lineageTag: 0b7b9169-abda-4426-b363-5cee4708a2d2
		sourceLineageTag: academic_period_key
		summarizeBy: none
		sourceColumn: academic_period_key

		annotation SummarizationSetBy = Automatic

	column program_key
		dataType: int64
		formatString: 0
		lineageTag: ebe87603-6f5c-46a3-a6a5-70097a4e3c6b
		sourceLineageTag: program_key
		summarizeBy: none
		sourceColumn: program_key

		annotation SummarizationSetBy = Automatic

	column enroll_date_key
		dataType: int64
		formatString: 0
		lineageTag: d7b3f050-ae47-45ab-ab4e-78204e5d11ec
		sourceLineageTag: enroll_date_key
		summarizeBy: none
		sourceColumn: enroll_date_key

		annotation SummarizationSetBy = Automatic

	column withdraw_date_key
		dataType: double
		lineageTag: eea8f544-149c-4c10-b701-53f6e68a7e9e
		sourceLineageTag: withdraw_date_key
		summarizeBy: sum
		sourceColumn: withdraw_date_key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column enrollment_status
		dataType: string
		lineageTag: 8d30ed98-0590-47cc-9ccb-f67d5540fe30
		sourceLineageTag: enrollment_status
		summarizeBy: none
		sourceColumn: enrollment_status

		annotation SummarizationSetBy = Automatic

	column enrollment_type
		dataType: string
		lineageTag: ada5b202-30b0-44fb-91fb-4252c5fd5879
		sourceLineageTag: enrollment_type
		summarizeBy: none
		sourceColumn: enrollment_type

		annotation SummarizationSetBy = Automatic

	column delivery_mode
		dataType: string
		lineageTag: 1cd1702d-4cba-4375-870e-b0db85927f03
		sourceLineageTag: delivery_mode
		summarizeBy: none
		sourceColumn: delivery_mode

		annotation SummarizationSetBy = Automatic

	column course_final_grade_letter
		dataType: string
		lineageTag: fe8c5907-9d43-4d13-acd1-7e71029ff377
		sourceLineageTag: course_final_grade_letter
		summarizeBy: none
		sourceColumn: course_final_grade_letter

		annotation SummarizationSetBy = Automatic

	column course_gpa_points
		dataType: double
		lineageTag: 8bab7858-e9df-4294-9f6d-19b3b27c235b
		sourceLineageTag: course_gpa_points
		summarizeBy: sum
		sourceColumn: course_gpa_points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_points_attempted
		dataType: int64
		formatString: 0
		lineageTag: ca932256-4908-4b93-9d23-8c54abfe4fc1
		sourceLineageTag: credit_points_attempted
		summarizeBy: sum
		sourceColumn: credit_points_attempted

		annotation SummarizationSetBy = Automatic

	column credit_points_earned
		dataType: int64
		formatString: 0
		lineageTag: 2d15ba6f-e218-49d9-a3ce-e399b5c94689
		sourceLineageTag: credit_points_earned
		summarizeBy: sum
		sourceColumn: credit_points_earned

		annotation SummarizationSetBy = Automatic

	column is_repeat
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 752fa71b-e922-4188-a593-7bec2f4b4487
		sourceLineageTag: is_repeat
		summarizeBy: none
		sourceColumn: is_repeat

		annotation SummarizationSetBy = Automatic

	column withdrew_before_census
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a18e04b8-d144-47de-85bf-dfc57bc04bcf
		sourceLineageTag: withdrew_before_census
		summarizeBy: none
		sourceColumn: withdrew_before_census

		annotation SummarizationSetBy = Automatic

	column academic_load
		dataType: double
		lineageTag: 9988198f-c0d0-438a-ba20-916a75d5c6ff
		sourceLineageTag: academic_load
		summarizeBy: sum
		sourceColumn: academic_load

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_enrollments = entity
		mode: directLake
		source
			entityName: fact_enrollments
			schemaName: university
			expressionSource: 'DirectLake - university_lakehouse'

